name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_2024 }}

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extra Cargo
      run: cargo install cargo-caw-publish
    - name: Run tests
      run: cargo test
    - name: Build
      run: cargo build --profile release
    - name: Publish to crates.io
      run: cargo caw-publish

